"""init

Revision ID: 557eb5540b2a
Revises: a08baad6e1ba
Create Date: 2025-07-01 13:24:03.628640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '557eb5540b2a'
down_revision: Union[str, Sequence[str], None] = 'a08baad6e1ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('game_results_mvp_fkey'), 'game_results', type_='foreignkey')
    op.drop_constraint(op.f('game_results_impostor_fkey'), 'game_results', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('game_results_impostor_fkey'), 'game_results', 'players', ['impostor'], ['id'])
    op.create_foreign_key(op.f('game_results_mvp_fkey'), 'game_results', 'players', ['mvp'], ['id'])
    # ### end Alembic commands ###
